BOARD_SIZE = 6 + 1
GAME_BOARD_SIZE = 6

# состояния точек:
DOT_IS_EMPTY = -5
DOT_IS_SHIP = -4
DOT_IS_FORBIDDEN_FOR_SHIP = -3
DOT_IS_MISS = -2
DOT_IS_HIT = -1
DOT_IS_SKIPPED = 0

# типы кораблей:
SINGLE = 1
DOUBLE = 2
TRIPLE = 3
QUARTER = 4

# состояния кораблей:
SHIP_IS_WHOLE = 5
SHIP_IS_DAMAGED = 6
SHIP_IS_DEAD = 7

# типы расположений кораблей:
SHIP_IS_VERTICAL = 8
SHIP_IS_HORIZONTAL = 9

# ограничения:
MAX_SHIP_SIZE = 4

MAX_SINGLE_COUNT = 4
MAX_DOUBLE_COUNT = 2
MAX_TRIPLE_COUNT = 1
MAX_QUARTER_COUNT = 0

DOT_STATES = (DOT_IS_EMPTY, DOT_IS_MISS, DOT_IS_HIT, DOT_IS_SKIPPED)
SHIP_STATES = (SHIP_IS_WHOLE, SHIP_IS_DAMAGED, SHIP_IS_DEAD)
SHIP_VALID_AMOUNT = {SINGLE: MAX_SINGLE_COUNT,
                     DOUBLE: MAX_DOUBLE_COUNT,
                     TRIPLE: MAX_TRIPLE_COUNT,
                     QUARTER: MAX_QUARTER_COUNT
                     }

SHIP_SIZES = (QUARTER, TRIPLE, DOUBLE, SINGLE)

range_ = range(1, BOARD_SIZE)