# Generated by Django 4.2 on 2023-04-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='location',
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
