# Generated by Django 4.2 on 2023-04-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_author_bio_remove_author_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='user_id',
        ),
    ]
