# Generated by Django 4.2 on 2023-04-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_user_author_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_id',
            new_name='user',
        ),
    ]
