# Generated by Django 4.2 on 2023-04-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_user_id_author_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
