# Generated by Django 4.2 on 2023-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_post_remove_author_birth_date_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'Article'), ('NE', 'New')], default='NE', max_length=2),
        ),
    ]
