# Generated by Django 4.1.7 on 2023-09-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorysubscribers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorysubscribers',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adverts.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('tnk', 'Танки'), ('hl', 'Хилы'), ('dd', 'ДД'), ('trd', 'Торговцы'), ('gm', 'Гилдмастеры'), ('qst', 'Квестгиверы'), ('bsm', 'Кузнецы'), ('skn', 'Кожевники'), ('zlv', 'Зельевары'), ('mst', 'Мастера заклинаний')], default='tnk', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategorySubscribers',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
